<a href="https://colab.research.google.com/github/adekunleba/tensorflow_tutorial/blob/master/IntroductiontoTensorflowOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### About Tensorflow

*Assumptions:*
 - Good Python background
 - Good knowledge of Machine learning
 - Little understanding of Neural Networks
 
 
 Tensorflow is a **software library** for machine Intelligence. This means it's a library that allows you to build artificial intelligence projects easily.
 
 
 What Artificial Intelligence projects entails - it entails a lot of deep mathematical computation. To merge the tensorflow as a library to Artificial Intelligence, Tensorflow has been described as an Open source software library for **numerical computation** using data flow graphs.
 
 
 Initially, Tensorflow requires you to build a graph first, then execute a graph in a Session, howevever, Tensorflow has upgraded to a state where the graph  building has been abstracted, hence, the defacto for Tensorflow is to use the Eager Execution mode, where you don't have to build a graph and execute in seperate code build up.


Tensorflow computation is based on computation on Tensors. Tensors are in short multi-dimensional Arrays.

Tensorflow programs use a data structure called Tensor to represent all of the data.

Because of the way numerical computation for Artificial Intelligence models are represented, Tensoflow leverages the use of Graph to express the computations i.e All numerical computations are expressed as computational graph.

![alt text](https://drive.google.com/open?id=10OdVIzD3AKVf-4AWWpzDGMdm-ycoCQM9)

### Starting with the Eager Execution mode in Tensorflow

In [0]:
import tensorflow as tf
tf.enable_eager_execution()

With the Eager Execution we can use Tensorflow to do some basic Mathematics similar to what we have with Numpy.

In [0]:
#Add 2-Scalar Entitites

print(tf.add(1, 2))


#Multiply 2-Scalar Entities
print(tf.multiply(2, 3))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


In [0]:
#Add 2-D Vector Entities

print(tf.add([[1, 2], 
              [2, 3]], [[5, 4],
                        [6, 7]]))

#Multiply 2-D Vector Entities

print(tf.multiply([[1, 2], 
                   [2, 3]], [[5, 4],
                            [6, 7]]))

tf.Tensor(
[[ 6  6]
 [ 8 10]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 5  8]
 [12 21]], shape=(2, 2), dtype=int32)


### Some other Basic Mathematical Operations with Tensorflow

In [0]:
#Square a scalar and Vector
print(tf.square(10))
print(tf.square([[2, 3], [5,4]]))

tf.Tensor(100, shape=(), dtype=int32)
tf.Tensor(
[[ 4  9]
 [25 16]], shape=(2, 2), dtype=int32)


In [0]:
#Get the mean of 1-D and 2-D array of Number
print(tf.reduce_mean([1, 2, 3, 4, 5, 6, 7, 7,8 , 6, 6, 3, 2, 2]))

print(tf.reduce_mean([[10, 10, 3], 
                      [40, 5, 6], 
                      [5, 6, 6]], axis=0, keepdims=True))

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([[18  7  5]], shape=(1, 3), dtype=int32)


In [0]:
#Get the minimum value in a 1-D Array
print(tf.reduce_min([1, 2, 3, 4, 5, 6, 7, 7,8 , 6, 6, 3, 2, 2]))


#Get the minimum value in a 2-D Tensor along a particular axis
print(tf.reduce_min([[10, 10, 3], 
                     [40, 5, 6], 
                     [5, 6, 6]], axis=1, keepdims=True))

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(
[[3]
 [5]
 [5]], shape=(3, 1), dtype=int32)


In [0]:
#Generating Random Numbers 

x = tf.random_uniform([4, 4])
print(x)


#Creating Tensor Constants in Eager Execution
y = tf.constant([[10, 10, 3], 
                     [40, 5, 6], 
                     [5, 6, 6]])

print(y)

tf.Tensor(
[[0.5771668  0.8151798  0.8233317  0.09823287]
 [0.03514731 0.77169764 0.5021397  0.93847215]
 [0.37982666 0.96519697 0.22838175 0.7515241 ]
 [0.12786257 0.5004227  0.74379385 0.11298704]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[10 10  3]
 [40  5  6]
 [ 5  6  6]], shape=(3, 3), dtype=int32)


In [0]:
#Calculate Sigmoid of an Array of Numbers

sig = tf.sigmoid(x)

print(sig)

tf.Tensor(
[[0.6404152  0.6932122  0.6949431  0.52453846]
 [0.5087859  0.683888   0.62296206 0.71879095]
 [0.5938313  0.72416115 0.5568485  0.6795107 ]
 [0.53192216 0.62255865 0.6778249  0.5282167 ]], shape=(4, 4), dtype=float32)


In [0]:
print(tf.test.is_gpu_available())
